CREATE TABLE history (
	rule_number	INTEGER		PRIMARY KEY 	AUTOINCREMENT,
	time		TIMESTAMP		NOT NULL 	DEFAULT 	CURRENT_TIMESTAMP,
	dimension	INTEGER		NOT NULL	DEFAULT	2,
	interest	INTEGER		NOT NULL	DEFAULT	2,
	rule		VARCHAR(255)		NOT NULL 	DEFAULT 	'',
	image		VARCHAR(255)		NOT NULL 	DEFAULT 	''
	);
 	