CREATE TABLE history (
	rule_number	INTEGER 		PRIMARY KEY 	AUTOINCREMENT,
	rule		VARCHAR(255) 		NOT NULL 	DEFAULT 	'',
	image		VARCHAR(255) 		NOT NULL 	DEFAULT 	'',
	time		TIMESTAMP 		NOT NULL 	DEFAULT 	CURRENT_TIMESTAMP
	);

CREATE TABLE examples AS SELECT * FROM history WHERE 0;